#ifndef NETWORK_H
#define NETWORK_H

#include <stdlib.h>
#include "neuron.h"

typedef struct network {
  /*TODO*/
} network;

/*initializes all errors to 0, and final layers' errors as appropriate
 *nw - network to initialize
 */
void init_errors(network* nw);

/*flows information forward to compute
 *nw - network to forward propagate
 */
void forward_propagate(network* nw);

/*flows errors backward to train
 *nw - network to backpropagate
*/
void back_propagate(network* nw);

#endif /*NETWORK_H*/
